jobs:
  stage_0_job_0:
    name: cli ros2-ros2cli rosidl-cli ros2cli
    runs-on: macos-15
    strategy:
      fail-fast: false
    needs: []
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
    - name: Build ros2-rosidl-cli ros2-ros2cli ros-rolling-rosidl-cli ros-rolling-ros2cli
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros2-rosidl-cli ros2-ros2cli ros-rolling-rosidl-cli ros-rolling-ros2cli
        BUILD_TARGET: osx-arm64
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
    permissions:
      id-token: write
      attestations: write
name: build_osx_arm64
on:
  push:
    branches:
    - buildbranch_osx_arm64
